### ISSUE TITLE
negative spacing

### ISSUE THREAD

**Issue by efflam** [tachyons-css/tachyons-spacing#6]
Hi,
What do yo think about negative margins (mh-1 mh-2 ...) ?
That would allow something like this:

```
<div class="flex flex-wrap mh-2">
  <div class="ph2 w-100 w-50-m w-33-l">
    item 1
  </div>
  <div class="ph2 w-100 w-50-m w-33-l">
    item 2
  </div>
  <div class="ph2 w-100 w-50-m w-33-l">
    item 3
  </div>
  <div class="ph2 w-100 w-50-m w-33-l">
    item 4
  </div>
</div>

```

**Comment by frolic** [comment]
Alternatively `.mhn1` etc. (`n` being negative).

**Comment by mrmrs** [comment]
Planning no adding negative margins but it will be in a separate module.

**Comment by mrkhdly** [comment]
https://github.com/tachyons-css/tachyons-negative-margins
